/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import javax.swing.JFrame;

/**
 *
 * @author Johnny e Rodrigo
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FrmMenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
        //setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MenuPrincipal = new javax.swing.JMenuBar();
        MenuCadastros = new javax.swing.JMenu();
        MenuClientes = new javax.swing.JMenuItem();
        MenuFuncionarios = new javax.swing.JMenuItem();
        MenuVeiculos = new javax.swing.JMenuItem();
        MenuDestinos = new javax.swing.JMenuItem();
        MenuEstoque = new javax.swing.JMenu();
        MenuConsultaCliente = new javax.swing.JMenuItem();
        MenuConsultaFuncionario = new javax.swing.JMenuItem();
        MenuConsultaVeiculos = new javax.swing.JMenuItem();
        MenuConsultaDestinos = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        MenuCadastros.setText("Cadastros");

        MenuClientes.setText("Clientes");
        MenuClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuClientesActionPerformed(evt);
            }
        });
        MenuCadastros.add(MenuClientes);

        MenuFuncionarios.setText("Funcionarios");
        MenuFuncionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuFuncionariosActionPerformed(evt);
            }
        });
        MenuCadastros.add(MenuFuncionarios);

        MenuVeiculos.setText("Veículos");
        MenuVeiculos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuVeiculosActionPerformed(evt);
            }
        });
        MenuCadastros.add(MenuVeiculos);

        MenuDestinos.setText("Destinos");
        MenuDestinos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuDestinosActionPerformed(evt);
            }
        });
        MenuCadastros.add(MenuDestinos);

        MenuPrincipal.add(MenuCadastros);

        MenuEstoque.setText("Consultas");

        MenuConsultaCliente.setText("Clientes");
        MenuConsultaCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuConsultaClienteActionPerformed(evt);
            }
        });
        MenuEstoque.add(MenuConsultaCliente);

        MenuConsultaFuncionario.setText("Funcionario");
        MenuConsultaFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuConsultaFuncionarioActionPerformed(evt);
            }
        });
        MenuEstoque.add(MenuConsultaFuncionario);

        MenuConsultaVeiculos.setText("Veículos");
        MenuConsultaVeiculos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuConsultaVeiculosActionPerformed(evt);
            }
        });
        MenuEstoque.add(MenuConsultaVeiculos);

        MenuConsultaDestinos.setText("Destinos");
        MenuConsultaDestinos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuConsultaDestinosActionPerformed(evt);
            }
        });
        MenuEstoque.add(MenuConsultaDestinos);

        MenuPrincipal.add(MenuEstoque);

        setJMenuBar(MenuPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuClientesActionPerformed
        ListaClientes obj = new ListaClientes();
        obj.setVisible(true);        
    }//GEN-LAST:event_MenuClientesActionPerformed

    private void MenuFuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuFuncionariosActionPerformed
         CadastroUsuario user = new CadastroUsuario();
         user.setVisible(true);
         
    }//GEN-LAST:event_MenuFuncionariosActionPerformed

    private void MenuVeiculosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuVeiculosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuVeiculosActionPerformed

    private void MenuDestinosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuDestinosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuDestinosActionPerformed

    private void MenuConsultaClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuConsultaClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuConsultaClienteActionPerformed

    private void MenuConsultaFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuConsultaFuncionarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuConsultaFuncionarioActionPerformed

    private void MenuConsultaVeiculosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuConsultaVeiculosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuConsultaVeiculosActionPerformed

    private void MenuConsultaDestinosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuConsultaDestinosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuConsultaDestinosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu MenuCadastros;
    private javax.swing.JMenuItem MenuClientes;
    private javax.swing.JMenuItem MenuConsultaCliente;
    private javax.swing.JMenuItem MenuConsultaDestinos;
    private javax.swing.JMenuItem MenuConsultaFuncionario;
    private javax.swing.JMenuItem MenuConsultaVeiculos;
    private javax.swing.JMenuItem MenuDestinos;
    private javax.swing.JMenu MenuEstoque;
    private javax.swing.JMenuItem MenuFuncionarios;
    private javax.swing.JMenuBar MenuPrincipal;
    private javax.swing.JMenuItem MenuVeiculos;
    // End of variables declaration//GEN-END:variables
}
